### ISSUE TITLE
Vivecraft and Embeddium non compat crash

### ISSUE THREAD

**Issue by YukiRainee** [ferriarnus/VivecraftForge#258] opened 2024-02-27 08:42 UTC
First of all I know this is a duplicate of #247 and #243 along with #252 this is just more of logging the issue, I took the liberty of looking over at their github repo and the issue popped up there but was closed and was explained that the issue is on vivecraft's side [#198](https://github.com/embeddedt/embeddium/issues/198) with them linking the code here https://github.com/Vivecraft/VivecraftMod/blob/471f2151e904d629c22b144cbaa4925ea0bad75b/common/src/main/java/org/vivecraft/mod_compat_vr/sodium/SodiumHelper.java#L41-L70

With the explanation being that 

> [embeddedt](https://github.com/embeddedt) commented [3 weeks ago](https://github.com/embeddedt/embeddium/issues/198#issuecomment-1929629384)
ViveCraft is accessing internal Sodium classes [here](https://github.com/Vivecraft/VivecraftMod/blob/471f2151e904d629c22b144cbaa4925ea0bad75b/common/src/main/java/org/vivecraft/mod_compat_vr/sodium/SodiumHelper.java#L41-L70); this needs to be fixed on their end. 

https://mclo.gs/CubH2zi

**Comment by fayer3** [comment] 2024-02-27 12:34
I know what the issue is, and it's already fixed with 1.1.7, available for testing in the vivecraft discords

**Comment by YukiRainee** [comment] 2024-02-27 17:48
Ahh did not know that I will hop in the discord and grab the latest version

**Comment by fayer3** [comment] 2024-02-29 01:11
fixed with 1.1.7, now available

**Closed as completed by fayer3** 2024-02-29 01:11 UTC
