### ISSUE TITLE
Crash when using Sodium 0.5.8

### ISSUE THREAD

**Issue by MarijnIsN00B** [ferriarnus/VivecraftForge#247] opened 2024-02-11 14:34 UTC
My game is crashing every time I enter a world using Sodium 0.5.8 and Vivecraft 1.1.5 on Fabric 1.20.1
Crash log: https://mclo.gs/zWCQnp2
I assume this is because 1.1.6 isn't backported to 1.20.1?

**Comment by fayer3** [comment] 2024-02-11 14:36
yes, the compat stuff isn't backported yet. duplicate of #243

**Comment by DarianLStephens** [comment] 2024-02-12 10:44
What's the recommended version to use in the meantime, then?

**Comment by fayer3** [comment] 2024-02-12 13:22
0.5.3

**Comment by Rainee4563** [comment] 2024-02-27 08:34
took a look over at [#198](https://github.com/embeddedt/embeddium/issues/198) seems like its the blame game

**Comment by fayer3** [comment] 2024-02-29 01:12
fixed with 1.1.7, now available

**Closed as completed by fayer3** 2024-02-29 01:12 UTC
Labels: bug, mod compatibility
