### ISSUE TITLE
Image stops being sent to the headset when joining a server with a custom resource pack

### ISSUE THREAD

**Issue by Ryhon0** [ferriarnus/VivecraftForge#254] opened 2024-02-24 16:50 UTC
When joining a server with server resource packs enabled, the game stops being rendered to the headset and is still being rendered in the window with all the logic working perfectly.
Disabling resource packs for a server fixes this but some servers make heavy use of resource packs and won't let you in without it.
Tested for 1.20.2 and 1.20.4 with Vivecraft 1.1.6 fabric on Linux with SteamVR streamed using ALVR on Linux

**Comment by fayer3** [comment] 2024-02-24 17:05
should be fixed, by togling vr once on the server, can be done with `right control + F7`

**Comment by fayer3** [comment] 2024-10-09 11:44
closing as duplicate of  #280, because the other one has a bit more info

**Closed as completed by fayer3** 2024-10-09 11:44 UTC
Labels: bug, rendering
