### ISSUE TITLE
Smoothcoasters support :P

### ISSUE THREAD

**Issue by adriansh05** [ferriarnus/VivecraftForge#289] opened 2024-07-29 07:30 UTC
Hi! I'm not sure if I should place this here or on a vivecraft page, so I will post this on both. But it would be really awesome if Smoothcoasters worked in vr! I tried doing it on Imaginefun (server) which supports smoothcoasters, but it seemed to make my vision a little cross and facing downwards or in a direction that I'm not looking in. I attempted this in both seated and standing mode. I understand if you are unable to make it compatible, I would just want to put this out there! :)

**Comment by fayer3** [comment] 2024-07-29 12:59
link to the mod for reference https://modrinth.com/mod/smoothcoasters

**Comment by fayer3** [comment] 2024-10-09 11:52
duplicate of #166

**Closed as completed by fayer3** 2024-10-09 11:52 UTC
Labels: mod compatibility
