### ISSUE TITLE
Incompatibility/bug with Minecraft Essentials

### ISSUE THREAD

**Issue by GZDaemon** [ferriarnus/VivecraftForge#180] opened 2023-08-20 10:18 UTC
I can't start my VR multiplayer world with a friend using the Essentials mod. It basically doesn't allow me to open my world for multiplayer while I have the VR headset on, with noVR mode this doesn't happen. 
(This shows up as "starting integrated server" but never opens).
This problem has a strange solution, and that is that once I am inside the world (in VR mode), if I suspend my VR headset and return to the computer, it allows me to open the world in multiplayer when the game is set to normal mode, If I turn on my headset again I can start playing with someone in my world.

I'm playing minecraft version 1.19.2 with Fabric, the mod version is "vivecraft-1.19.2-1.0.1-fabric" attached the latest log (if it's useful).
I report this here, because it seems that this incompatibility comes from this mod, I attach the video on youtube and this image.

https://www.youtube.com/watch?v=ZwphJQ3DRik
![vlcsnap-2023-08-20-03h29m40s030](https://github.com/ferriarnus/VivecraftMod/assets/142720590/bcd3f304-fcb6-47ea-b41c-851798a9599d)
[latest.log](https://github.com/ferriarnus/VivecraftMod/files/12387916/latest.log)

**Comment by fayer3** [comment] 2023-08-20 10:37
known issuey a workaround is to let the game run for some time with VR completely off  or hotswitched off

**Comment by GZDaemon** [comment] 2023-08-21 00:11
> known issuey a workaround is to let the game run for some time with VR completely off or hotswitched off

I will keep it in mind.

I think that at this point, the quickest solution is to suspend the VR headset and return to the PC to open the world in multiplayer in normal mode and return to VR and that's it.
It's a pretty weird bug to be honest.

**Comment by fayer3** [comment] 2023-08-21 00:12
the issue is that we replace the original runtick method, it's probably fixable

**Comment by fayer3** [comment] 2023-09-26 14:58
fixed with c61b00c06cc35c34011ea02018e2c15ca16e29bc

**Closed as completed by fayer3** 2023-09-26 14:58 UTC
